[build]
  command = "ionic build --prod"
  publish = "www"

[context.production.environment]
  NODE_VERSION = "18.x"  # Especifique a versão do Node.js que você está usando

  # Caso queira evitar problemas com versões mais recentes do Python:
  # PYTHON_VERSION = "3.7"
